In [131]:
# -*- coding: utf-8 -*-
import numpy as np
import matplotlib.pyplot as plt

train = np.loadtxt("click.csv",delimiter=",",skiprows=1)

In [132]:
train_x = train[:,0]
train_y = train[:,1]

In [133]:
mu = train_x.mean()
sigma = train_x.std()

In [134]:
print(mu,sigma)

141.6 66.98537153737374


In [135]:
def standardize(x):
    return (x - mu) / sigma

In [136]:
train_x = standardize(train_x)

In [137]:
def to_matrix(x):
    return np.vstack([np.ones(x.size),x,x**2]).T

In [138]:
to_matrix(train_x)

array([[ 1.        ,  1.39433428,  1.94416809],
       [ 1.        ,  1.11069026,  1.23363286],
       [ 1.        ,  0.09554325,  0.00912851],
       [ 1.        , -1.59139223,  2.53252924],
       [ 1.        , -0.8449606 ,  0.71395842],
       [ 1.        ,  0.93154667,  0.8677792 ],
       [ 1.        , -1.38239138,  1.91100592],
       [ 1.        , -1.74067856,  3.02996185],
       [ 1.        ,  0.46875906,  0.21973506],
       [ 1.        ,  0.73747445,  0.54386856],
       [ 1.        , -0.11345761,  0.01287263],
       [ 1.        , -0.63595975,  0.4044448 ],
       [ 1.        , -0.36724436,  0.13486842],
       [ 1.        , -0.44188752,  0.19526458],
       [ 1.        ,  0.3045441 ,  0.09274711],
       [ 1.        ,  1.94669369,  3.78961632],
       [ 1.        ,  0.25975821,  0.06747433],
       [ 1.        ,  0.25975821,  0.06747433],
       [ 1.        , -1.23310505,  1.52054807],
       [ 1.        ,  0.84197488,  0.70892169]])

In [139]:
theta = np.random.rand(3)

In [140]:
theta

array([0.16507929, 0.37152766, 0.61361756])

In [141]:
def f(x):
    return np.dot(x,theta)

In [142]:
X = to_matrix(train_x)

In [143]:
f(X)

array([1.87608873, 1.33471023, 0.20617766, 1.12783747, 0.28925048,
       1.0436592 , 0.82410945, 1.37760686, 0.47406954, 0.77279875,
       0.13082552, 0.17697708, 0.11139548, 0.12072363, 0.3351371 ,
       3.21370496, 0.30299008, 0.30299008, 0.63998165, 0.91290304])

In [144]:
def E(x,y):
    return 0.5*np.sum((y - f(x))**2)

In [145]:
E(X,train_y)

1931003.6884611791

In [146]:
f(X)

array([1.87608873, 1.33471023, 0.20617766, 1.12783747, 0.28925048,
       1.0436592 , 0.82410945, 1.37760686, 0.47406954, 0.77279875,
       0.13082552, 0.17697708, 0.11139548, 0.12072363, 0.3351371 ,
       3.21370496, 0.30299008, 0.30299008, 0.63998165, 0.91290304])

In [148]:
# 学習率
ETA = 1e-3
# 誤差の差分
diff = 1
# 更新回数
count = 0
# 誤差の差分が0.01以下になるまでパラメータ更新を繰り返す
error = E(X, train_y)
while diff > 1e-2:
    # 更新結果を一時変数に保存
    theta = theta - ETA * np.dot(f(X) - train_y, X)

    # 前回の誤差との差分を計算
    current_error = E(X, train_y)
    diff = error - current_error
    error = current_error

    # ログの出力
    count += 1
    log = '{}回目: theta = {}, 差分 = {:.4f}'
    print(log.format(count, theta, diff))

# プロットして確認
x = np.linspace(-3, 3, 100)
plt.plot(train_z, train_y, 'o')
plt.plot(x, f(to_matrix(x)))
plt.show()

1回目: theta = [8.73250535 2.23452366 9.57976829], 差分 = 153230.2457
2回目: theta = [16.94925988  4.07269743 17.98651318], 差分 = 137958.7053
3回目: theta = [24.83354442  5.8857694  25.86520369], 差分 = 124293.6737
4回目: theta = [32.40256945  7.67350912 33.24546094], 差分 = 112064.0157
5回目: theta = [39.67260885  9.43573179 40.15527095], 差分 = 101116.8872
6回目: theta = [46.65905125 11.17229518 46.62107472], 差分 = 91315.7787
7回目: theta = [53.37644873 12.88309654 52.66785327], 差分 = 82538.7674
8回目: theta = [59.83856269 14.56806986 58.31920806], 差分 = 74676.9566
9回目: theta = [66.05840728 16.22718317 63.59743696], 差分 = 67633.0827
10回目: theta = [72.04829039 17.86043607 68.523606  ], 差分 = 61320.2700
11回目: theta = [77.81985246 19.46785742 73.11761725], 差分 = 55660.9203
12回目: theta = [83.38410307 21.04950306 77.39827293], 差分 = 50585.7202
13回目: theta = [88.75145555 22.60545383 81.38333592], 差分 = 46032.7549
14回目: theta = [93.93175972 24.1358136  85.08958709], 差分 = 41946.7174
15回目: theta = [98.93433278 25.64070742 88

NameError: name 'train_z' is not defined

In [ ]:
E_current,E_new